export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER-REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER-SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER-FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER-REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER-SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER-FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
