export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER-REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER-SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER-FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER-REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER-SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER-FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE-REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE-SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE-RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE-FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD-REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD-SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD-FAIL";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD-RESET";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD-REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD-SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD-FAIL";

export const NEW_PASSWORD_REQUEST = "NEW_PASSWORD-REQUEST";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD-SUCCESS";
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD-FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
